---
#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#######################################
# Start the job on all push to master #
#######################################
name: "Test Plugin"
on:
  push: # Comment this line to trigger action only on pull-requests (not recommended if you don't pay for GH Actions)
  pull_request:
    branches: [master, main]

###############
# Set the Job #
###############
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"
          # Defaults to the user or organization that owns the workflow file
          scope: "rubenhalman"

      # Install sfdx-cli
      - run: npm i sfdx-cli -g

      # Link plugin
      - run: echo y | sfdx plugins:install lightning-flow-scanner

      # Check plugin is correctly compiled
      - run: sfdx flow:scan

